# Generated by Django 5.2.16 on 2026-07-19 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date_worn", models.DateField()),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "log entries",
                "ordering": ["-date_worn", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LogEntryPolish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("base", "Base"), ("topper", "Topper"), ("accent", "Accent")],
                        default="base",
                        max_length=10,
                    ),
                ),
                (
                    "log_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entry_polishes",
                        to="wearlog.logentry",
                    ),
                ),
                (
                    "polish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.polish"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "log entry polishes",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="logentry",
            name="polishes",
            field=models.ManyToManyField(
                related_name="log_entries", through="wearlog.LogEntryPolish", to="catalog.polish"
            ),
        ),
        migrations.CreateModel(
            name="LogPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.ImageField(upload_to="log/")),
                (
                    "log_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="wearlog.logentry",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="logentrypolish",
            constraint=models.UniqueConstraint(
                fields=("log_entry", "polish", "role"), name="unique_polish_role_per_entry"
            ),
        ),
    ]
