# Generated by Django 5.2.16 on 2026-07-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wearlog", "0002_logentry_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logphoto",
            name="image",
            field=models.ImageField(max_length=250, upload_to="log/"),
        ),
    ]
