# Generated by Django 5.2.16 on 2026-07-19 09:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("website", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                (
                    "hex_color",
                    models.CharField(
                        blank=True,
                        help_text="Dot colour for this family's filter chip.",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a colour as #rrggbb, e.g. #1f6e6e.",
                                regex="^#(?:[0-9a-fA-F]{6})$",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Formula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=40, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to="catalog.brand",
                    ),
                ),
            ],
            options={
                "ordering": ["brand__name", "-year", "name"],
            },
        ),
        migrations.CreateModel(
            name="Polish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("webshop_link", models.URLField(blank=True)),
                (
                    "hex_color",
                    models.CharField(
                        default="#8a8a8a",
                        help_text="Base swatch colour, e.g. #1f6e6e. Finish effects layer on top of this.",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a colour as #rrggbb, e.g. #1f6e6e.",
                                regex="^#(?:[0-9a-fA-F]{6})$",
                            )
                        ],
                    ),
                ),
                (
                    "catalog_code",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to auto-generate from the brand, e.g. HT-014.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "in_collection",
                    models.BooleanField(
                        default=True, help_text="Unticked means it was owned once but no longer is."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="polishes",
                        to="catalog.brand",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="polishes",
                        to="catalog.collection",
                    ),
                ),
                ("colors", models.ManyToManyField(related_name="polishes", to="catalog.color")),
                ("formulas", models.ManyToManyField(related_name="polishes", to="catalog.formula")),
                (
                    "tags",
                    models.ManyToManyField(blank=True, related_name="polishes", to="catalog.tag"),
                ),
            ],
            options={
                "verbose_name_plural": "polishes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PolishPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.ImageField(upload_to="polishes/")),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "polish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="catalog.polish",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.UniqueConstraint(
                fields=("brand", "name"), name="unique_collection_per_brand"
            ),
        ),
    ]
