# Generated by Django 5.2.16 on 2026-07-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_add_thermal_formula"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polishphoto",
            name="image",
            field=models.ImageField(max_length=250, upload_to="polishes/"),
        ),
    ]
