# Generated by Django 5.2.16 on 2026-07-25 11:03

from django.db import migrations, models


def backfill_release_year(apps, schema_editor):
    """Seed the new mandatory year from the collection's year where a polish has one.
    Polishes without a collection are left blank for the user to fill in on next edit."""
    Polish = apps.get_model("catalog", "Polish")
    for polish in Polish.objects.filter(collection__year__isnull=False).select_related(
        "collection"
    ):
        polish.release_year = polish.collection.year
        polish.save(update_fields=["release_year"])


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_polishphoto_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="polish",
            name="release_day",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="polish",
            name="release_month",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="polish",
            name="release_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_release_year, migrations.RunPython.noop),
    ]
