# Generated by Django 5.2.16 on 2026-07-26 10:05

from django.db import migrations, models
from django.utils.text import slugify


def backfill_slugs(apps, schema_editor):
    Polish = apps.get_model("catalog", "Polish")
    for polish in Polish.objects.all().iterator():
        polish.slug = slugify(polish.name) or "polish"
        polish.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_polish_release_day_polish_release_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="polish",
            name="slug",
            field=models.SlugField(blank=True, max_length=160),
        ),
        migrations.RunPython(backfill_slugs, migrations.RunPython.noop),
    ]
